let animalEmpathy = document.getElementById('animalEmpathy');
let animalEmpathyPlus = document.getElementById('animalEmpathyPlus');
let animalEmpathyMinus = document.getElementById('animalEmpathyMinus');
let alchemyLabel = document.getElementById('alchemyLabel');
let alchemyPlus = document.getElementById('alchemyPlus');
let alchemyMinus = document.getElementById('alchemyMinus');
let handleAnimal = document.getElementById('handleAnimal');
let handleAnimalPlus = document.getElementById('handleAnimalPlus');
let handleAnimalMinus = document.getElementById('handleAnimalMinus');
let pickPocket = document.getElementById('pickPocket');
let pickPocketPlus = document.getElementById('pickPocketPlus');
let pickPocketMinus = document.getElementById('pickPocketMinus');
let heal = document.getElementById('heal');
let healPlus = document.getElementById('healPlus');
let healMinus = document.getElementById('healMinus');
let profession = document.getElementById('profession');
let professionPlus = document.getElementById('professionPlus');
let professionMinus = document.getElementById('professionMinus');
let appraiseLabel = document.getElementById('appraiseLabel');
let appraisePlus = document.getElementById('appraisePlus');
let appraiseMinus = document.getElementById('appraiseMinus');
let hide = document.getElementById('hide');
let hidePlus = document.getElementById('hidePlus');
let hideMinus = document.getElementById('hideMinus');
let readLips = document.getElementById('readLips');
let readLipsPlus = document.getElementById('readLipsPlus');
let readLipsMinus = document.getElementById('readLipsMinus');
let balance = document.getElementById('balance');
let balancePlus = document.getElementById('balancePlus');
let balanceMinus = document.getElementById('balanceMinus');
let innuendo = document.getElementById('innuendo');
let innuendoPlus = document.getElementById('innuendoPlus');
let innuendoMinus = document.getElementById('innuendoMinus');
let ride = document.getElementById('ride');
let ridePlus = document.getElementById('ridePlus');
let rideMinus = document.getElementById('rideMinus');
let bluffLabel = document.getElementById('bluffLabel');
let bluffPlus = document.getElementById('bluffPlus');
let bluffMinus = document.getElementById('bluffMinus');
let intimidate = document.getElementById('intimidate');
let intimidatePlus = document.getElementById('intimidatePlus');
let intimidateMinus = document.getElementById('intimidateMinus');
let scry = document.getElementById('scry');
let scryPlus = document.getElementById('scryPlus');
let scryMinus = document.getElementById('scryMinus');
let climb = document.getElementById('climb');
let climbPlus = document.getElementById('climbPlus');
let climbMinus = document.getElementById('climbMinus');
let intuitDirection = document.getElementById('intuitDirection');
let intuitDirectionPlus = document.getElementById('intuitDirectionPlus');
let intuitDirectionMinus = document.getElementById('intuitDirectionMinus');
let search = document.getElementById('search');
let searchPlus = document.getElementById('searchPlus');
let searchMinus = document.getElementById('searchMinus');
let craft = document.getElementById('craft');
let craftPlus = document.getElementById('craftPlus');
let craftMinus = document.getElementById('craftMinus');
let jump = document.getElementById('jump');
let jumpPlus = document.getElementById('jumpPlus');
let jumpMinus = document.getElementById('jumpMinus');
let senseMotive = document.getElementById('senseMotive');
let senseMotivePlus = document.getElementById('senseMotivePlus');
let senseMotiveMinus = document.getElementById('senseMotiveMinus');
let concentration = document.getElementById('concentration');
let concentrationPlus = document.getElementById('concentrationPlus');
let concentrationMinus = document.getElementById('concentrationMinus');
let knowledgeArcana = document.getElementById('knowledgeArcana');
let knowledgeArcanaPlus = document.getElementById('knowledgeArcanaPlus');
let knowledgeArcanaMinus = document.getElementById('knowledgeArcanaMinus');
let speakLanguage = document.getElementById('speakLanguage');
let speakLanguagePlus = document.getElementById('speakLanguagePlus');
let speakLanguageMinus = document.getElementById('speakLanguageMinus');
let decipherScript = document.getElementById('decipherScript');
let decipherScriptPlus = document.getElementById('decipherScriptPlus');
let decipherScriptMinus = document.getElementById('decipherScriptMinus');
let knowledgeReligion = document.getElementById('knowledgeReligion');
let knowledgeReligionPlus = document.getElementById('knowledgeReligionPlus');
let knowledgeReligionMinus = document.getElementById('knowledgeReligionMinus');
let spellcraft = document.getElementById('spellcraft');
let spellcraftPlus = document.getElementById('spellcraftPlus');
let spellcraftMinus = document.getElementById('spellcraftMinus');
let diplomacy = document.getElementById('diplomacy');
let diplomacyPlus = document.getElementById('diplomacyPlus');
let diplomacyMinus = document.getElementById('diplomacyMinus');
let knowledgeNature = document.getElementById('knowledgeNature');
let knowledgeNaturePlus = document.getElementById('knowledgeNaturePlus');
let knowledgeNatureMinus = document.getElementById('knowledgeNatureMinus');
let spot = document.getElementById('spot');
let spotPlus = document.getElementById('spotPlus');
let spotMinus = document.getElementById('spotMinus');
let disableDevice = document.getElementById('disableDevice');
let disableDevicePlus = document.getElementById('disableDevicePlus');
let disableDeviceMinus = document.getElementById('disableDeviceMinus');
let knowledgeAllSkills = document.getElementById('knowledgeAllSkills');
let knowledgeAllSkillsPlus = document.getElementById('knowledgeAllSkillsPlus');
let knowledgeAllSkillsMinus = document.getElementById('knowledgeAllSkillsMinus');
let swim = document.getElementById('swim');
let swimPlus = document.getElementById('swimPlus');
let swimMinus = document.getElementById('swimMinus');
let disguise = document.getElementById('disguise');
let disguisePlus = document.getElementById('disguisePlus');
let disguiseMinus = document.getElementById('disguiseMinus');
let listen = document.getElementById('listen');
let listenPlus = document.getElementById('listenPlus');
let listenMinus = document.getElementById('listenMinus');
let tumble = document.getElementById('tumble');
let tumblePlus = document.getElementById('tumblePlus');
let tumbleMinus = document.getElementById('tumbleMinus');
let escapeArtist = document.getElementById('escapeArtist');
let escapeArtistPlus = document.getElementById('escapeArtistPlus');
let escapeArtistMinus = document.getElementById('escapeArtistMinus');
let moveSilently = document.getElementById('moveSilently');
let moveSilentlyPlus = document.getElementById('moveSilentlyPlus');
let moveSilentlyMinus = document.getElementById('moveSilentlyMinus');
let useMagicDevice = document.getElementById('useMagicDevice');
let useMagicDevicePlus = document.getElementById('useMagicDevicePlus');
let useMagicDeviceMinus = document.getElementById('useMagicDeviceMinus');
let forgery = document.getElementById('forgery');
let forgeryPlus = document.getElementById('forgeryPlus');
let forgeryMinus = document.getElementById('forgeryMinus');
let openLock = document.getElementById('openLock');
let openLockPlus = document.getElementById('openLockPlus');
let openLockMinus = document.getElementById('openLockMinus');
let useRope = document.getElementById('useRope');
let useRopePlus = document.getElementById('useRopePlus');
let useRopeMinus = document.getElementById('useRopeMinus');
let gatherInformation = document.getElementById('gatherInformation');
let gatherInformationPlus = document.getElementById('gatherInformationPlus');
let gatherInformationMinus = document.getElementById('gatherInformationMinus');
let perform = document.getElementById('perform');
let performPlus = document.getElementById('performPlus');
let performMinus = document.getElementById('performMinus');
let wildernessLore = document.getElementById('wildernessLore');
let wildernessLorePlus = document.getElementById('wildernessLorePlus');
let wildernessLoreMinus = document.getElementById('wildernessLoreMinus');

function changeSkillsForClass(){

    if(chosenClass == "Barbarian"){
        animalEmpathy.setAttribute("style", "background-color: red");
        animalEmpathyPlus.disabled = true;
        animalEmpathyMinus.disabled = true;
        decipherScript.setAttribute("style", "background-color: red");
        decipherScriptPlus.disabled = true;
        decipherScriptMinus.disabled = true;
        readLips.setAttribute("style", "background-color: red");
        readLipsPlus.disabled = true;
        readLipsMinus.disabled = true;
        scry.setAttribute("style", "background-color: red");
        scryPlus.disabled = true;
        scryMinus.disabled = true;
        useMagicDevice.setAttribute("style", "background-color: red");
        useMagicDevicePlus.disabled = true;
        useMagicDeviceMinus.disabled = true;
        alchemyLabel.setAttribute("style", "background-color: yellow");
        appraiseLabel.setAttribute("style", "background-color: yellow");
        balance.setAttribute("style", "background-color: yellow");
        bluffLabel.setAttribute("style", "background-color: yellow");
        concentration.setAttribute("style", "background-color: yellow");
        diplomacy.setAttribute("style", "background-color: yellow");
        disableDevice.setAttribute("style", "background-color: yellow");
        disguise.setAttribute("style", "background-color: yellow");
        escapeArtist.setAttribute("style", "background-color: yellow");
        forgery.setAttribute("style", "background-color: yellow");
        gatherInformation.setAttribute("style", "background-color: yellow");
        heal.setAttribute("style", "background-color: yellow");
        hide.setAttribute("style", "background-color: yellow");
        innuendo.setAttribute("style", "background-color: yellow");
        knowledgeAllSkills.setAttribute("style", "background-color: yellow");
        knowledgeArcana.setAttribute("style", "background-color: yellow");
        knowledgeNature.setAttribute("style", "background-color: yellow");
        knowledgeReligion.setAttribute("style", "background-color: yellow");
        moveSilently.setAttribute("style", "background-color: yellow");
        openLock.setAttribute("style", "background-color: yellow");
        perform.setAttribute("style", "background-color: yellow");
        pickPocket.setAttribute("style", "background-color: yellow");
        profession.setAttribute("style", "background-color: yellow");
        search.setAttribute("style", "background-color: yellow");
        senseMotive.setAttribute("style", "background-color: yellow");
        speakLanguage.setAttribute("style", "background-color: yellow");
        spellcraft.setAttribute("style", "background-color: yellow");
        spot.setAttribute("style", "background-color: yellow");
        tumble.setAttribute("style", "background-color: yellow");
        useRope.setAttribute("style", "background-color: yellow");
    }
    else  if(chosenClass == "Bard"){
            animalEmpathy.setAttribute("style", "background-color: red");
            animalEmpathyPlus.disabled = true;
            animalEmpathyMinus.disabled = true;
            readLips.setAttribute("style", "background-color: red");
            readLipsPlus.disabled = true;
            readLipsMinus.disabled = true;
            disableDevice.setAttribute("style", "background-color: yellow");
            forgery.setAttribute("style", "background-color: yellow");
            handleAnimal.setAttribute("style", "background-color: yellow");
            heal.setAttribute("style", "background-color: yellow");
            innuendo.setAttribute("style", "background-color: yellow");
            intimidate.setAttribute("style", "background-color: yellow");
            openLock.setAttribute("style", "background-color: yellow");
            ride.setAttribute("style", "background-color: yellow");
            search.setAttribute("style", "background-color: yellow");
            spot.setAttribute("style", "background-color: yellow");
            useRope.setAttribute("style", "background-color: yellow");
            wildernessLore.setAttribute("style", "background-color: yellow");
    }
    else if(chosenClass == "Cleric"){
            animalEmpathy.setAttribute("style", "background-color: red");
            animalEmpathyPlus.disabled = true;
            animalEmpathyMinus.disabled = true;
            decipherScript.setAttribute("style", "background-color: red");
            decipherScriptPlus.disabled = true;
            decipherScriptMinus.disabled = true;
            readLips.setAttribute("style", "background-color: red");
            readLipsPlus.disabled = true;
            readLipsMinus.disabled = true;
            useMagicDevice.setAttribute("style", "background-color: red");
            useMagicDevicePlus.disabled = true;
            useMagicDeviceMinus.disabled = true;
            alchemyLabel.setAttribute("style", "background-color: yellow");
            appraiseLabel.setAttribute("style", "background-color: yellow");
            balance.setAttribute("style", "background-color: yellow");
            bluffLabel.setAttribute("style", "background-color: yellow");
            climb.setAttribute("style", "background-color: yellow");
            disableDevice.setAttribute("style", "background-color: yellow");
            disguise.setAttribute("style", "background-color: yellow");
            escapeArtist.setAttribute("style", "background-color: yellow");
            forgery.setAttribute("style", "background-color: yellow");
            gatherInformation.setAttribute("style", "background-color: yellow");
            handleAnimal.setAttribute("style", "background-color: yellow");
            hide.setAttribute("style", "background-color: yellow");
            innuendo.setAttribute("style", "background-color: yellow");
            intimidate.setAttribute("style", "background-color: yellow");
            intuitDirection.setAttribute("style", "background-color: yellow");
            jump.setAttribute("style", "background-color: yellow");
            knowledgeNature.setAttribute("style", "background-color: yellow");
            knowledgeAllSkills.setAttribute("style", "background-color: yellow");
            listen.setAttribute("style", "background-color: yellow");
            moveSilently.setAttribute("style", "background-color: yellow");
            openLock.setAttribute("style", "background-color: yellow");
            perform.setAttribute("style", "background-color: yellow");
            pickPocket.setAttribute("style", "background-color: yellow");
            ride.setAttribute("style", "background-color: yellow");
            search.setAttribute("style", "background-color: yellow");
            senseMotive.setAttribute("style", "background-color: yellow");
            speakLanguage.setAttribute("style", "background-color: yellow");
            spot.setAttribute("style", "background-color: yellow");
            swim.setAttribute("style", "background-color: yellow");
            tumble.setAttribute("style", "background-color: yellow");
            useRope.setAttribute("style", "background-color: yellow");
            wildernessLore.setAttribute("style", "background-color: yellow");
    }
    else if(chosenClass == "Druid"){
                decipherScript.setAttribute("style", "background-color: red");
                decipherScriptPlus.disabled = true;
                decipherScriptMinus.disabled = true;
                readLips.setAttribute("style", "background-color: red");
                readLipsPlus.disabled = true;
                readLipsMinus.disabled = true;
                useMagicDevice.setAttribute("style", "background-color: red");
                useMagicDevicePlus.disabled = true;
                useMagicDeviceMinus.disabled = true;
                alchemyLabel.setAttribute("style", "background-color: yellow");
                appraiseLabel.setAttribute("style", "background-color: yellow");
                balance.setAttribute("style", "background-color: yellow");
                bluffLabel.setAttribute("style", "background-color: yellow");
                climb.setAttribute("style", "background-color: yellow");
                disableDevice.setAttribute("style", "background-color: yellow");
                disguise.setAttribute("style", "background-color: yellow");
                escapeArtist.setAttribute("style", "background-color: yellow");
                forgery.setAttribute("style", "background-color: yellow");
                gatherInformation.setAttribute("style", "background-color: yellow");
                hide.setAttribute("style", "background-color: yellow");
                innuendo.setAttribute("style", "background-color: yellow");
                intimidate.setAttribute("style", "background-color: yellow");
                jump.setAttribute("style", "background-color: yellow");
                knowledgeArcana.setAttribute("style", "background-color: yellow");
                knowledgeReligion.setAttribute("style", "background-color: yellow");
                knowledgeAllSkills.setAttribute("style", "background-color: yellow");
                listen.setAttribute("style", "background-color: yellow");
                moveSilently.setAttribute("style", "background-color: yellow");
                openLock.setAttribute("style", "background-color: yellow");
                perform.setAttribute("style", "background-color: yellow");
                pickPocket.setAttribute("style", "background-color: yellow");
                ride.setAttribute("style", "background-color: yellow");
                scry.setAttribute("style", "background-color: yellow");
                senseMotive.setAttribute("style", "background-color: yellow");
                speakLanguage.setAttribute("style", "background-color: yellow");
                spot.setAttribute("style", "background-color: yellow");
                tumble.setAttribute("style", "background-color: yellow");
                useRope.setAttribute("style", "background-color: yellow");
    }
        else if(chosenClass == "Fighter"){
            animalEmpathy.setAttribute("style", "background-color: red");
            animalEmpathyPlus.disabled = true;
            animalEmpathyMinus.disabled = true;
            decipherScript.setAttribute("style", "background-color: red");
            decipherScriptPlus.disabled = true;
            decipherScriptMinus.disabled = true;
            readLips.setAttribute("style", "background-color: red");
            readLipsPlus.disabled = true;
            readLipsMinus.disabled = true;
            scry.setAttribute("style", "background-color: red");
            scryPlus.disabled = true;
            scryMinus.disabled = true;
            useMagicDevice.setAttribute("style", "background-color: red");
            useMagicDevicePlus.disabled = true;
            useMagicDeviceMinus.disabled = true;
            alchemyLabel.setAttribute("style", "background-color: yellow");
            appraiseLabel.setAttribute("style", "background-color: yellow");
            balance.setAttribute("style", "background-color: yellow");
            bluffLabel.setAttribute("style", "background-color: yellow");
            concentration.setAttribute("style", "background-color: yellow");
            diplomacy.setAttribute("style", "background-color: yellow");
            disableDevice.setAttribute("style", "background-color: yellow");
            disguise.setAttribute("style", "background-color: yellow");
            escapeArtist.setAttribute("style", "background-color: yellow");
            forgery.setAttribute("style", "background-color: yellow");
            gatherInformation.setAttribute("style", "background-color: yellow");
            heal.setAttribute("style", "background-color: yellow");
            hide.setAttribute("style", "background-color: yellow");
            innuendo.setAttribute("style", "background-color: yellow");
            intimidate.setAttribute("style", "background-color: yellow");
            intuitDirection.setAttribute("style", "background-color: yellow");
            knowledgeAllSkills.setAttribute("style", "background-color: yellow");
            knowledgeReligion.setAttribute("style", "background-color: yellow");
            knowledgeArcana.setAttribute("style", "background-color: yellow");
            knowledgeNature.setAttribute("style", "background-color: yellow");
            listen.setAttribute("style", "background-color: yellow");
            moveSilently.setAttribute("style", "background-color: yellow");
            openLock.setAttribute("style", "background-color: yellow");
            perform.setAttribute("style", "background-color: yellow");
            pickPocket.setAttribute("style", "background-color: yellow");
            profession.setAttribute("style", "background-color: yellow");
            search.setAttribute("style", "background-color: yellow");
            senseMotive.setAttribute("style", "background-color: yellow");
            speakLanguage.setAttribute("style", "background-color: yellow");
            spot.setAttribute("style", "background-color: yellow");
            tumble.setAttribute("style", "background-color: yellow");
            useRope.setAttribute("style", "background-color: yellow");
            wildernessLore.setAttribute("style", "background-color: yellow");
        }
}
