let animalEmpathy = document.getElementById('animalEmpathy');
let animalEmpathyPlus = document.getElementById('animalEmpathyPlus');
let animalEmpathyMinus = document.getElementById('animalEmpathyMinus');
let alchemyLabel = document.getElementById('alchemyLabel');
let handleAnimal = document.getElementById('handleAnimal');
let pickPocket = document.getElementById('pickPocket');
let heal = document.getElementById('heal');
let profession = document.getElementById('profession');
let appraiseLabel = document.getElementById('appraiseLabel');
let hide = document.getElementById('hide');
let readLips = document.getElementById('readLips');
let balance = document.getElementById('balance');
let innuendo = document.getElementById('innuendo');
let ride = document.getElementById('ride');
let bluffLabel = document.getElementById('bluffLabel');
let intimidate = document.getElementById('intimidate');
let scry = document.getElementById('scry');
let climb = document.getElementById('climb');
let intuitDirection = document.getElementById('intuitDirection');
let search = document.getElementById('search');
let craft = document.getElementById('craft');
let jump = document.getElementById('jump');
let senseMotive = document.getElementById('senseMotive');
let concentration = document.getElementById('concentration');
let knowledgeArcana = document.getElementById('knowledgeArcana');
let speakLanguage = document.getElementById('speakLanguage');
let decipherScript = document.getElementById('decipherScript');
let knowledgeReligion = document.getElementById('knowledgeReligion');
let spellcraft = document.getElementById('spellcraft');
let diplomacy = document.getElementById('diplomacy');
let knowledgeNature = document.getElementById('knowledgeNature');
let spot = document.getElementById('spot');
let disableDevice = document.getElementById('disableDevice');
let knowledgeAllSkills = document.getElementById('knowledgeAllSkills');
let swim = document.getElementById('swim');
let disguise = document.getElementById('disguise');
let listen = document.getElementById('listen');
let tumble = document.getElementById('tumble');
let escapeArtistPlus = document.getElementById('escapeArtistPlus');
let moveSilently = document.getElementById('moveSilently');
let useMagicDevice = document.getElementById('useMagicDevice');
let forgery = document.getElementById('forgery');
let openLock = document.getElementById('openLock');
let useRope = document.getElementById('useRope');
let gatherInformation = document.getElementById('gatherInformation');
let perform = document.getElementById('perform');
let wildernessLore = document.getElementById('wildernessLore');

function changeSkillsForClass(){

    if(chosenClass == "Barbarian"){
        animalEmpathy.setAttribute("style", "background-color: red");
        animalEmpathyPlus.disabled = true;
        animalEmpathyMinus.disabled = true;
        decipherScript.setAttribute("style", "background-color: red");
        readLips.setAttribute("style", "background-color: red");
        scry.setAttribute("style", "background-color: red");
        useMagicDevice.setAttribute("style", "background-color: red");
        alchemyLabel.setAttribute("style", "background-color: yellow");
        appraiseLabel.setAttribute("style", "background-color: yellow");
        balance.setAttribute("style", "background-color: yellow");
        bluffLabel.setAttribute("style", "background-color: yellow");
        concentration.setAttribute("style", "background-color: yellow");
        diplomacy.setAttribute("style", "background-color: yellow");
        disableDevice.setAttribute("style", "background-color: yellow");
        disguise.setAttribute("style", "background-color: yellow");
        escapeArtist.setAttribute("style", "background-color: yellow");
        forgery.setAttribute("style", "background-color: yellow");
        gatherInformation.setAttribute("style", "background-color: yellow");
        heal.setAttribute("style", "background-color: yellow");
        hide.setAttribute("style", "background-color: yellow");
        innuendo.setAttribute("style", "background-color: yellow");
        knowledgeAllSkills.setAttribute("style", "background-color: yellow");
        knowledgeArcana.setAttribute("style", "background-color: yellow");
        knowledgeNature.setAttribute("style", "background-color: yellow");
        knowledgeReligion.setAttribute("style", "background-color: yellow");
        moveSilently.setAttribute("style", "background-color: yellow");
        openLock.setAttribute("style", "background-color: yellow");
        perform.setAttribute("style", "background-color: yellow");
        pickPocket.setAttribute("style", "background-color: yellow");
        profession.setAttribute("style", "background-color: yellow");
        search.setAttribute("style", "background-color: yellow");
        senseMotive.setAttribute("style", "background-color: yellow");
        speakLanguage.setAttribute("style", "background-color: yellow");
        spellcraft.setAttribute("style", "background-color: yellow");
        spot.setAttribute("style", "background-color: yellow");
        tumble.setAttribute("style", "background-color: yellow");
        useRope.setAttribute("style", "background-color: yellow");
    }
}
